### ISSUE TITLE
[ENHANCEMENT] create/add a script for certificate generation

### ISSUE THREAD

**Issue by hackacad** [smortex/freebsd-ports#4]
Create a small sh script for automatic certificate generation 

INPUT: country, region, e-mail, etc.
OUTPUT: admin.pem, admin-key.pem, root-ca.pem

**Comment by smortex** [comment]
Hum, I am not sure:

On one hand, the "bootstrap" script `/usr/local/lib/opensearch/plugins/opensearch-security/tools/install_demo_configuration.sh` is cool because it allows you to start doing things "instantaneously" but these settings are only good for a POC.

On the other hand, in a real-world™ enterpriseⓡ production™ environment you probably want your nodes certificates to be part of an existing PKI.

Also, the OpenSearch documentation has extensive instructions for generating certificates: https://opensearch.org/docs/security-plugin/configuration/generate-certificates/

So I am not sure if we need one more "source for certificates" ?

**Comment by smortex** [comment]
I just realize that the comments added in the sample `opensearch.yml` file prevent `install_demo_configuration.sh` from doing it's job.

Maybe we should remove these comments and add a note to the post-install message to tell the user to look at the script?

**Comment by hackacad** [comment]
> I just realize that the comments added in the sample `opensearch.yml` file prevent `install_demo_configuration.sh` from doing it's job.
> 
> Maybe we should remove these comments and add a note to the post-install message to tell the user to look at the script?

fixed in https://github.com/smortex/freebsd-ports/commit/328faf0673e7101fe003c544d6743091cecb4b5d#diff-fe8e1ce3c5b667194ea29f0a120e6b0707872643d6c71397b4071b8272a0b40d

**Comment by smortex** [comment]
Thanks!  Do you also want to add a note in the post-installation message?

**Comment by smortex** [comment]
I think we are good with this issue?
